server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/
          searchPaths: config-data
          default-label: mainTURAMADEGIT
  security:
    user:
      name: bustamante
      password: carpio
